# Generated by Django 4.1.3 on 2022-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
